# Generated by Django 2.0.4 on 2018-08-30 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("music", "0001_initial")]

    operations = [
        migrations.AlterField(
            model_name="audio",
            name="album",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tracks",
                to="music.Album",
            ),
        )
    ]
