# Generated by Django 2.1.7 on 2019-10-08 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_auto_20191007_2036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audio',
            name='is_listed',
        ),
    ]
