# Generated by Django 2.1.7 on 2019-10-09 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("music", "0004_remove_audio_is_listed")]

    operations = [
        migrations.RemoveField(model_name="audiocompilation", name="tracks"),
        migrations.DeleteModel(name="AudioCompilation"),
    ]
