# Generated by Django 2.1.7 on 2019-10-15 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0009_auto_20191012_1743'),
    ]

    operations = [
        migrations.AddField(
            model_name='artistevent',
            name='title',
            field=models.CharField(default='Event', max_length=256),
            preserve_default=False,
        ),
    ]
