# Generated by Django 2.1.7 on 2019-10-20 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0010_artistevent_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='spreadshirt_shop_slug',
            field=models.SlugField(blank=True, max_length=256, null=True),
        ),
    ]
