# Generated by Django 2.1.7 on 2019-10-21 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("music", "0012_auto_20191021_0131"),
    ]

    operations = [
        migrations.AddField(
            model_name="album",
            name="record_label_tag",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
