# Generated by Django 2.1.7 on 2020-01-21 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("music", "0015_auto_20191025_1806"),
    ]

    operations = [
        migrations.AddField(
            model_name="album",
            name="youtube_tag",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
