# Generated by Django 4.2.11 on 2024-04-09 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("music", "0017_auto_20200120_2340"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="artist",
            name="managers",
        ),
        migrations.RemoveField(
            model_name="artist",
            name="spreadshirt_shop_slug",
        ),
    ]
