# Generated by Django 4.2.11 on 2024-04-12 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("music", "0018_remove_artist_managers_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="album",
            name="_youtube_tag_rendered",
        ),
        migrations.RemoveField(
            model_name="album",
            name="record_label_tag",
        ),
        migrations.RemoveField(
            model_name="album",
            name="youtube_tag",
        ),
    ]
