# Generated by Django 2.1.7 on 2019-10-23 04:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ContactForm",
            fields=[
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("contact_info", models.CharField(max_length=256)),
                ("subject", models.CharField(max_length=256)),
                ("body", models.CharField(max_length=2000)),
            ],
            options={
                "ordering": ("-created",),
            },
        ),
    ]
