# Generated by Django 2.1.7 on 2019-10-23 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contact", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contactform",
            name="body",
            field=models.TextField(max_length=2000),
        ),
    ]
