"""
Django settings for punkweb project.

Generated by 'django-admin startproject' using Django 4.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get(
    "SECRET_KEY", "360wd#k-r^(p)o*86&yw00&^z#x!eoozkq=bn@r!4da7bfnodf"
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.humanize",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.postgres",
    "django_extensions",
    "easy_thumbnails",
    "rest_framework",
    # PunkwebBB
    "precise_bbcode",
    "punkweb_bb",
    # Punkweb
    "apps.analytics",
    "apps.contact",
    "apps.music",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "punkweb_bb.middleware.ProfileOnlineCacheMiddleware",
]

ROOT_URLCONF = "punkweb.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "punkweb_bb.context_processors.punkweb_bb",
            ]
        },
    }
]

WSGI_APPLICATION = "punkweb.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": "punkweb",
        "USER": "punkweb",
        "PASSWORD": os.environ.get("DB_PASSWORD", "punkweb"),
        "HOST": "localhost",
        "PORT": "5432",
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"
    },
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "America/New_York"

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = "static/"


# Media files

STATIC_URL = "/static/"
MEDIA_URL = "/media/"

if DEBUG:
    STATIC_ROOT = BASE_DIR / "server" / "dev" / "static"
    MEDIA_ROOT = BASE_DIR / "server" / "dev" / "media"
else:
    STATIC_ROOT = "/var/www/punkweb.us/static/"
    MEDIA_ROOT = "/var/www/punkweb.us/media/"


# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# Non default app configuration

# admin.site.site_header = 'Punk Web'

LOGIN_REDIRECT_URL = "/board/"

CORS_ORIGIN_ALLOW_ALL = True

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework.authentication.TokenAuthentication",
        "punkweb.rest.authentication.NoCSRFSessionAuthentication",
    ),
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 25,
}

THUMBNAIL_ALIASES = {
    "": {
        "avatar_lrg_no_crop": {"size": (400, 400), "crop": False},
        "avatar_no_crop": {"size": (200, 200), "crop": False},
        "avatar_small_no_crop": {"size": (100, 100), "crop": False},
        "avatar_smaller_no_crop": {"size": (50, 50), "crop": False},
        "avatar_smallest_no_crop": {"size": (25, 25), "crop": False},
        "avatar_lrg": {"size": (400, 400), "crop": True},
        "avatar": {"size": (200, 200), "crop": True},
        "avatar_small": {"size": (100, 100), "crop": True},
        "avatar_smaller": {"size": (50, 50), "crop": True},
        "avatar_smallest": {"size": (25, 25), "crop": True},
    }
}
