# Generated by Django 2.1.7 on 2019-10-22 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='analyticsevent',
            options={'ordering': ('-occurred_at',)},
        ),
    ]
