# Generated by Django 2.1.7 on 2019-11-20 02:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_auto_20191021_2115'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientError',
            fields=[
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('error_body', models.CharField(max_length=2048)),
            ],
            options={
                'ordering': ('-occurred_at',),
            },
        ),
    ]
